const timesArrayKey = "pllTimesArray";
const selectionArrayKey = "pllSelection";
var trainerTitle = "Megaminx ZBLL Trainer";
var preRotations = [''];
var postRotations = [''];
var preMoves = ["", "U", "U'", "U2", "U2'"];
var postMoves = preMoves;
var selCases = [];
var maxAlgsPerRow = 6;